import Link from "next/link";
import { getAllPosts } from "../services/BlogPostService";
import Button from "@mui/material/Button";
import Hero from "../components/Hero";

//@ts-ignore
const Home = ({ posts }) => {
  return (
    <>
      <Hero />
      <h1>All Posts</h1>
      <p>
        Click the link below to navigate to a page generated by
        <code>mdx-bundler</code>.
      </p>
      <ul>
        {/* @ts-ignore */}
        {posts.map((post, index) => (
          <li key={index}>
            <Link passHref href={`/blog/${post.slug}`}>
              <Button variant="contained">{post.frontmatter.title}</Button>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const posts = getAllPosts();
  return {
    props: { posts },
  };
};
